services:
    mapper:
        image: mapper-image:latest
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./imgData:/App/imgData:rw